---
on:
  push:
    branches: [master]

name: MainBranch

permissions:
  contents: read

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      newtag: ${{ steps.calculate-version.outputs.version-string }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: master
          create_tag: true
          tag_prefix: 'v'
      - name: Use version
        run: 'echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"'

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "${{ steps.calculate-version.outputs.version-string }}"
          tag: "${{ steps.calculate-version.outputs.version-string }}"
  
  dockerhub:
      needs:
          - version
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/test:${{ needs.version.newtag }},${{ secrets.DOCKERHUB_USERNAME }}/test:latest"
          push: true

